import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';

export default function Home() {
  const [posts, setPosts] = React.useState([])

  const fetchPosts = () => {
    console.log('Coucou je fetche');
    fetch('http://localhost:3000/posts')
      .then(response => response.json())
      .then(response => {
        console.log(response);
        setPosts(response)
      })
  }

  React.useEffect(() => {fetchPosts()}, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Hello</h1>
      <div className="container">
        {posts.map(post =>
          <div className={`post-${post.id}`}>
            <h2>{post.title}</h2>
            <p>{post.content}</p>
          </div>
        )}
      </div>
    </div>
  )
}
