import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import PostCard from '../components/PostCard'
import Link from 'next/link'


export default function Home() {
  const [posts, setPosts] = React.useState([])

  const fetchPosts = () => {
    fetch('http://localhost:3000/posts')
      .then(response => response.json())
      .then(response => {
        console.log(response);
        setPosts(response)
      })
  }

  React.useEffect(() => {fetchPosts()}, [])

  return (
    <div>
      <Head>
        <title>Immo Coin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Hello</h1>
      <div className="grid grid-cols-3">
        {posts.map(post =>
                <Link key={post.id} href={`/posts/` +post.id}>
                  <a>{post.title}</a>
                </Link>

        
         // <PostCard data={post} key={post.id}/>
          
        )}
      </div>
    </div>
  )
}
